// frontend/src/pages/ReservationForm.jsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { toast, Toaster } from 'react-hot-toast';
import { motion, AnimatePresence } from 'framer-motion';


const API_BASE = 'https://reservation-backend-demo.onrender.com';

const generateTimeSlots = (start, end, interval) => {
  const slots = [];
  const [startH, startM] = start.split(':').map(Number);
  const [endH, endM] = end.split(':').map(Number);
  
  let current = new Date();
  current.setHours(startH, startM, 0, 0);
  
  const endTime = new Date();
  endTime.setHours(endH, endM, 0, 0);
  
  while (current <= endTime) {
    const timeString = current.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
    slots.push(timeString);
    current.setMinutes(current.getMinutes() + interval);
  }
  return slots;
};

const ReservationForm = () => {
  const { restaurantId } = useParams();
  const allowedRestaurants = ['Indian', 'Chinese', 'Italian', 'Oriental']; // ✅ only your actual restaurants
  const navigate = useNavigate();
  const { t, i18n } = useTranslation();
  const today = new Date();
  const menuUrl = `/menus/${restaurantId}.pdf`;
  const imageUrl = `/menus/${restaurantId}.png`;

  const [isSending, setIsSending] = useState(false);
  const [loadingCapacities, setLoadingCapacities] = useState(true);
  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
  const [spotsLeft, setSpotsLeft] = useState(null);
  const [capacities, setCapacities] = useState({});
  const [showSushiModal, setShowSushiModal] = useState(false);

  // NEW STATE
  const [restaurantConfig, setRestaurantConfig] = useState(null);
  const [availableTimeSlots, setAvailableTimeSlots] = useState([]);
  const [configLoading, setConfigLoading] = useState(true);

  const sushiItems = {
    hot_rolls: [
      { name: 'Hot Dynamites', price: 4 },
      { name: 'Hot Crab', price: 4 },
      { name: 'Hot Dragon', price: 4 }
    ],
    maki_rolls: [
      { name: 'Sake Maki', price: 3 },
      { name: 'Seagull Roll', price: 5 },
      { name: 'Kappa Roll', price: 2 },
      { name: 'Kabi Maki', price: 4 }
    ]
  };



  const [formData, setFormData] = useState({
    date: '',
    time: '19:00',
    guests: '',
    room: '',
    first_name: '',
    last_name: '',
    email: '',
    main_courses: [],
    comments: '',
    upsell_items: {}
  });

  if (!allowedRestaurants.includes(restaurantId)) {
    return (
      <div className="text-center text-2xl py-20 text-gray-700">
        {restaurantId} is not a valid restaurant.
      </div>
    );
  }



  useEffect(() => {
    const handleResize = () => setWindowWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  // ✅ Fetch capacities from direct backend
  useEffect(() => {
    const fetchCapacities = async () => {
      try {
        const res = await fetch(`${API_BASE}/capacities`);
        const data = await res.json();
        setCapacities(data);
      } catch (err) {
        console.error('Failed to fetch capacities:', err);
      } finally {
        setLoadingCapacities(false);
      }
    };

    fetchCapacities();
  }, []);

  // 🔄 Check spots when date changes
  useEffect(() => {
    const checkSpotsLeft = async () => {
      if (!formData.date || !restaurantId) return;

      try {
        const key = `${restaurantId}_${formData.date}`;
        const capacity = capacities[key];
        if (!capacity) {
          setSpotsLeft(null);
          return;
        }

        const res = await fetch(`${API_BASE}/reservations?restaurant=${restaurantId}&date=${formData.date}`);
        const data = await res.json();
        const totalGuests = data.totalGuests;

        const remaining = capacity - totalGuests;
        setSpotsLeft(remaining);
      } catch (error) {
        console.error('Error checking capacity:', error);
        setSpotsLeft(null);
      }
    };

    checkSpotsLeft();
  }, [formData.date, restaurantId, capacities]);

  // 🔄 Sync main_courses with number of guests
  useEffect(() => {
    const guests = parseInt(formData.guests);
    if (!isNaN(guests)) {
      const current = formData.main_courses || [];
      const updated = Array.from({ length: guests }, (_, i) => current[i] || '');
      setFormData(prev => ({ ...prev, main_courses: updated }));
    }
  }, [formData.guests]);

  // 1. FETCH CONFIG ON LOAD
  useEffect(() => {
    const fetchConfig = async () => {
      try {
        const res = await fetch(`${API_BASE}/api/v1/config`);
        const data = await res.json();
        const myConfig = data[restaurantId];
        
        if (myConfig) {
          setRestaurantConfig(myConfig);
          // Generate slots immediately if config exists
          const slots = generateTimeSlots(myConfig.openingTime, myConfig.closingTime, myConfig.intervalMinutes);
          setAvailableTimeSlots(slots);
          
          // Set default time to first slot if existing '19:00' isn't valid
          if (!slots.includes(formData.time)) {
            setFormData(prev => ({...prev, time: slots[0]}));
          }
        }
      } catch (e) {
        console.error("Config load failed", e);
      } finally {
        setConfigLoading(false);
      }
    };
    fetchConfig();
  }, [restaurantId]);

  const handleChange = (e) => {
    const { name, value } = e.target;

    if (name === 'guests') {
      const guestCount = Number(value);
      setFormData({
        ...formData,
        guests: guestCount,
        main_courses: Array(guestCount).fill(''),
      });
    } else {
      setFormData({
        ...formData,
        [name]: value,
      });
    }
  };

  // 1. Separate the actual API call into a new function
  const finalizeReservation = async (finalUpsellItems = formData.upsell_items) => {
    if (isSending) return;
    setIsSending(true);

    try {
      // Recalculate price based on final selection
      let upsell_total_price = 0;
      Object.entries(finalUpsellItems).forEach(([item, count]) => {
        if (count > 0) {
          Object.values(sushiItems).forEach(category => {
            category.forEach(sushi => {
              if (sushi.name === item) {
                upsell_total_price += sushi.price * count;
              }
            });
          });
        }
      });

      const response = await fetch(`${API_BASE}/api/v1/reservations`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...formData,
          restaurant: restaurantId,
          upsell_items: finalUpsellItems,
          upsell_total_price: Number(upsell_total_price.toFixed(2))
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || 'Reservation failed');
      }

      toast.success('Reservation confirmed! ✅');
      setTimeout(() => navigate('/confirmation'), 1500);
    } catch (error) {
      console.error('❌ Reservation Error:', error);
      toast.error(error.message);
    } finally {
      setIsSending(false);
      setShowSushiModal(false); // Close modal if open
    }
  };

  // 2. Intercept the form submit
  const handleSubmit = async (e) => {
    e.preventDefault();

    // Basic validation
    if (!formData.room || !formData.date) {
      toast.error(t('room_required'));
      return;
    }

    // Intercept Chinese Restaurant for Upsell
    if (restaurantId === 'Chinese') {
      // If they haven't selected anything yet, show the modal
      const hasSelectedSushi = Object.values(formData.upsell_items).some(val => val > 0);

      // logic: Always show modal if it hasn't been shown,
      // or specifically check if they want to review order.
      // Here we force the modal to appear to "Upsell"
      setShowSushiModal(true);
      return;
    }

    // For other restaurants, submit immediately
    await finalizeReservation();
  };

  const getDayLabel = (date) => {
    return date.toLocaleDateString(
      i18n.language === 'de' ? 'de-DE' :
        i18n.language === 'fr' ? 'fr-FR' :
          i18n.language === 'ru' ? 'ru-RU' : 'en-US',
      { weekday: 'long', month: 'long', day: 'numeric' }
    );
  };

  const isTodayBlocked = today.getHours() >= 11;

  // 2. CHECK IF RESTAURANT IS CLOSED
  if (!configLoading && restaurantConfig && !restaurantConfig.isActive) {
     return (
       <div className="max-w-4xl mx-auto pt-32 text-center p-6">
         <div className="bg-red-50 border border-red-200 text-red-700 p-8 rounded-xl">
           <h2 className="text-2xl font-bold mb-2">Restaurant Currently Closed</h2>
           <p>The {restaurantId} restaurant is not accepting new reservations at this time.</p>
           <button onClick={() => navigate('/')} className="mt-4 text-blue-600 underline">Back to Home</button>
         </div>
       </div>
     );
  }

  return (
    <div className="max-w-6xl mx-auto pt-24 md:pt-28 grid grid-cols-1 md:grid-cols-2 gap-6 p-4">
      <Toaster position="top-right" />

      {/* Left Side */}
      <div className="bg-white shadow rounded-2xl p-6 flex flex-col items-center">
        <h3 className="text-lg font-semibold text-gray-700 mb-4">{t('restaurant_menu')}</h3>
        {windowWidth < 768 ? (
          <img src={imageUrl} alt="Menu Cover" className="rounded-lg object-cover w-full h-auto max-h-[300px]" />
        ) : (
          <iframe src={menuUrl} className="w-full h-[500px] border rounded" title="Restaurant Menu" />
        )}
        <a href={menuUrl} target="_blank" rel="noopener noreferrer" className="mt-4 bg-[#006494] text-white px-4 py-2 rounded hover:bg-[#005377]">
          {t('menu_button')}
        </a>
      </div>

      {/* Right Side */}
      <div className="bg-white shadow rounded-2xl p-4 sm:p-8">
        <h2 className="text-2xl font-bold mb-6 text-gray-800">{t('book_table')}</h2>
        <form onSubmit={handleSubmit} className="space-y-4">


          {loadingCapacities ? (
            <select disabled className="w-full border p-2 rounded bg-gray-100 text-gray-500">
              <option>{t('loading available dates') || 'Loading available dates...'}</option>
            </select>
          ) : (
            <select name="date" value={formData.date} onChange={handleChange} required className="w-full border p-3 rounded-md">
              <option value="">{t('select_date')}</option>
              {[...Array(6)].map((_, index) => {
                const date = new Date();
                date.setDate(today.getDate() + index);
                const iso = date.toISOString().split('T')[0];
                const key = `${restaurantId}_${iso}`;
                const capacity = capacities[key];
                const isDisabled = (index === 0 && isTodayBlocked) || !capacity || capacity === 0;

                return (
                  <option key={iso} value={iso} disabled={isDisabled}>
                    {getDayLabel(date)}{isDisabled ? ' (Unavailable)' : ''}
                  </option>
                );
              })}
            </select>
          )}


          {spotsLeft !== null && spotsLeft <= 4 && spotsLeft > 0 && (
            <div className="text-yellow-600 text-sm mt-1">
              ⚠ Only {spotsLeft} spot{spotsLeft !== 1 ? 's' : ''} left for this date!
            </div>
          )}
          {spotsLeft === 0 && (
            <div className="text-red-600 text-sm mt-1">
              ❌ This date is fully booked.
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Time</label>
            <select
              name="time"
              value={formData.time}
              onChange={handleChange}
              required
              className="w-full border p-2 rounded bg-white"
            >
              {availableTimeSlots.length > 0 ? (
                availableTimeSlots.map(time => (
                  <option key={time} value={time}>
                    {time}
                  </option>
                ))
              ) : (
                <option value="19:00">19:00</option> // Fallback
              )}
            </select>
          </div>

          <select name="guests" value={formData.guests} onChange={handleChange} required className="w-full border p-2 rounded">
            <option value="">{t('number_of_guests')}</option>
            {[1, 2, 3, 4].map(num => <option key={num} value={num}>{num}</option>)}
          </select>

          <input type="number" name="room" value={formData.room} onChange={handleChange} required className="w-full border p-2 rounded" placeholder={t('room_number')} />
          <input type="text" name="first_name" value={formData.first_name} onChange={handleChange} className="w-1/2 border p-2 rounded" placeholder={t('first_name')} required />
          <input type="text" name="last_name" value={formData.last_name} onChange={handleChange} className="w-1/2 border p-2 rounded" placeholder={t('last_name')} required />
          <input type="email" name="email" value={formData.email} onChange={handleChange} required className="w-full border p-2 rounded" placeholder={t('email')} />

          {(restaurantId.toLowerCase() === 'chinese' || restaurantId.toLowerCase() === 'indian' || restaurantId.toLowerCase() === 'italian') && (
            <div>
              <label className="block text-gray-700 mb-2">
                {t('select_main_course')} (for each guest)
              </label>

              {[...Array(formData.guests || 0)].map((_, index) => (
                <div key={index} className="flex flex-col sm:flex-row sm:items-center gap-3 sm:gap-4 mb-3">
                  <span className="text-gray-600">Guest {index + 1}:</span>
                  {restaurantId.toLowerCase() === 'italian' ? (
                    <>
                      <button
                        type="button"
                        aria-pressed={formData.main_courses[index] === 'quatro_formagi'}
                        className={`w-full sm:w-auto px-4 py-3 border rounded-lg text-sm sm:text-base ${formData.main_courses[index] === 'quatro_formagi' ? 'bg-yellow-100 border-yellow-400 text-yellow-800' : 'bg-white hover:bg-gray-100'}`}
                        onClick={() => {
                          const updated = [...formData.main_courses];
                          updated[index] = 'quatro_formagi';
                          setFormData({ ...formData, main_courses: updated });
                        }}
                      >
                        {t('quatro_formagi') || 'Quatro Formagi'}
                      </button>
                      <button
                        type="button"
                        aria-pressed={formData.main_courses[index] === 'chicken_pizza'}
                        className={`w-full sm:w-auto px-4 py-3 border rounded-lg text-sm sm:text-base ${formData.main_courses[index] === 'chicken_pizza' ? 'bg-yellow-100 border-yellow-400 text-yellow-800' : 'bg-white hover:bg-gray-100'}`}
                        onClick={() => {
                          const updated = [...formData.main_courses];
                          updated[index] = 'chicken_pizza';
                          setFormData({ ...formData, main_courses: updated });
                        }}
                      >
                        {t('chicken_pizza') || 'Chicken Pizza'}
                      </button>
                      <button
                        type="button"
                        aria-pressed={formData.main_courses[index] === 'petto_chicken'}
                        className={`w-full sm:w-auto px-4 py-3 border rounded-lg text-sm sm:text-base ${formData.main_courses[index] === 'petto_chicken' ? 'bg-yellow-100 border-yellow-400 text-yellow-800' : 'bg-white hover:bg-gray-100'}`}
                        onClick={() => {
                          const updated = [...formData.main_courses];
                          updated[index] = 'petto_chicken';
                          setFormData({ ...formData, main_courses: updated });
                        }}
                      >
                        {t('petto_chicken') || 'Petto Chicken'}
                      </button>
                    </>
                  ) : (
                    <>
                      <button
                        type="button"
                        className={`px-4 py-2 border rounded-md ${formData.main_courses[index] === 'chicken' ? 'bg-yellow-100 border-yellow-400 text-yellow-800' : 'bg-white hover:bg-gray-100'}`}
                        onClick={() => {
                          const updated = [...formData.main_courses];
                          updated[index] = 'chicken';
                          setFormData({ ...formData, main_courses: updated });
                        }}
                      >
                        {t('chicken')}
                      </button>
                      <button
                        type="button"
                        className={`px-4 py-2 border rounded-md ${formData.main_courses[index] === 'meat' ? 'bg-yellow-100 border-yellow-400 text-yellow-800' : 'bg-white hover:bg-gray-100'}`}
                        onClick={() => {
                          const updated = [...formData.main_courses];
                          updated[index] = 'meat';
                          setFormData({ ...formData, main_courses: updated });
                        }}
                      >
                        {t('meat')}
                      </button>
                    </>
                  )}
                </div>
              ))}
            </div>
          )}
          {restaurantId.toLowerCase() === 'chinese' && (
            <>

              {/* Preview selected sushi items */}
              {Object.entries(formData.upsell_items)
                .filter(([_, count]) => count > 0)
                .length > 0 && (
                  <div className="bg-white border border-gray-200 p-4 rounded-xl shadow-sm mb-4">
                    <h4 className="text-sm font-semibold text-gray-800 mb-2">
                      🍣 {t('selected_sushi') || 'Selected Sushi Items'}
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {Object.entries(formData.upsell_items)
                        .filter(([_, count]) => count > 0)
                        .map(([item, count]) => (
                          <span
                            key={item}
                            className="inline-flex items-center bg-yellow-100 text-yellow-800 px-3 py-1 rounded-full text-sm"
                          >
                            {item} × {count}
                          </span>
                        ))}

                      {/* 💵 Show total sushi price */}
                      {(() => {
                        let total = 0;
                        Object.entries(formData.upsell_items).forEach(([item, count]) => {
                          if (count > 0) {
                            Object.values(sushiItems).forEach(category => {
                              category.forEach(sushi => {
                                if (sushi.name === item) {
                                  total += sushi.price * count;
                                }
                              });
                            });
                          }
                        });
                        return (
                          <div className="mt-2 text-sm font-semibold text-gray-700">
                            {t('total_price') || 'Total'}: ${total.toFixed(2)}
                            <div className="mt-2 text-sm text-red-600 font-medium">
                              {t('extra_charge_notice') || 'An extra charge will be added to your room.'}
                            </div>
                          </div>
                        );
                      })()}
                    </div>
                  </div>
                )}
            </>
          )}

          <textarea
            name="comments"
            value={formData.comments}
            onChange={handleChange}
            rows={3}
            maxLength={150}
            placeholder={t('comments_placeholder') || 'Special requests, allergies, etc.'}
            className="w-full border p-2 rounded"
          />


          <button type="submit" disabled={isSending} className={`w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 ${isSending ? 'opacity-50 cursor-not-allowed' : ''}`}>
            {isSending ? t('sending') : t('confirm_reservation')}
          </button>
        </form>
      </div>

      <AnimatePresence>
        {showSushiModal && (
          <motion.div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 px-4"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              transition={{ duration: 0.3 }}
              className="bg-white p-6 rounded-2xl w-full max-w-md shadow-xl relative max-h-[90vh] overflow-y-auto"
            >
              <button
                onClick={() => setShowSushiModal(false)}
                className="absolute top-2 right-3 text-gray-500 hover:text-gray-700 text-2xl"
              >
                &times;
              </button>

              <h3 className="text-xl font-bold mb-2 text-gray-800">Chef's Recommendation 🍣</h3>
              <p className="text-gray-600 mb-4 text-sm">Would you like to add some Sushi to your dinner?</p>

              {Object.entries(sushiItems).map(([category, items]) => (
                <div
                  key={category}
                  className="mb-6 bg-gray-50 p-4 rounded-xl shadow-inner border border-gray-200"
                >
                  <h4 className="text-xl font-bold text-blue-700 mb-4 border-b border-gray-300 pb-1 flex items-center gap-2">
                    {category === 'hot_rolls' ? '🍣' : '🍥'} {t(`sushi_categories.${category}`)}
                  </h4>

                  {items.map(({ name, description, price }) => {
                    const count = formData.upsell_items[name] || 0;
                    return (
                      <div
                        key={name}
                        className="flex justify-between items-center p-3 rounded-xl shadow-sm border mb-4 bg-white"
                      >
                        <div>
                          <span className="font-medium text-gray-800">{name}</span>
                          <p className="text-sm text-gray-600">
                            {t(`sushi_items.${name}.description`)} — ${price}
                          </p>
                        </div>
                        <div className="flex items-center gap-2">
                          <button
                            type="button"
                            onClick={() =>
                              setFormData((prev) => ({
                                ...prev,
                                upsell_items: {
                                  ...prev.upsell_items,
                                  [name]: Math.max((prev.upsell_items[name] || 0) - 1, 0),
                                },
                              }))
                            }
                            className="bg-gray-200 px-2 rounded text-lg"
                          >
                            -
                          </button>
                          <span className="min-w-[20px] text-center">{count}</span>
                          <button
                            type="button"
                            onClick={() =>
                              setFormData((prev) => ({
                                ...prev,
                                upsell_items: {
                                  ...prev.upsell_items,
                                  [name]: (prev.upsell_items[name] || 0) + 1,
                                },
                              }))
                            }
                            className="bg-gray-200 px-2 rounded text-lg"
                          >
                            +
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              ))}

              <div className="mt-6 flex gap-3">
                <button
                  onClick={() => {
                    // Option A: Skip Upsell (Clear selection and submit)
                    const emptyUpsell = {};
                    finalizeReservation(emptyUpsell);
                  }}
                  className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
                >
                  No, Thanks
                </button>

                <button
                  onClick={() => {
                    // Option B: Confirm Upsell
                    finalizeReservation(formData.upsell_items);
                  }}
                  className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-semibold"
                >
                  Add to Order
                </button>
              </div>

            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div >
  );
};

export default ReservationForm;

// hotel-reservation/src/app/features/guest/reservation-form/reservation-form.component.ts
// =================================================================================
// File: hotel-reservation/src/app/features/guest/reservation-form/reservation-form.component.ts
// =================================================================================

import { Component, OnInit, signal, ChangeDetectionStrategy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, FormArray, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { ToastrService } from 'ngx-toastr';
import { ReservationService } from '../../../core/services/reservation.service';
import { ConfigService } from '../../../core/services/config.service';
import { CapacityService } from '../../../core/services/capacity.service';
import { LoadingSpinner } from '../../../shared/components/loading-spinner/loading-spinner';
import { LucideAngularModule } from 'lucide-angular';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-reservation-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    TranslateModule,
    LoadingSpinner,
    LucideAngularModule
  ],
  changeDetection: ChangeDetectionStrategy.OnPush, // ✅ Performance Boost
  template: `
    <!-- Template remains exactly the same as previous iteration -->
    <div class="max-w-6xl mx-auto pt-24 md:pt-28 grid grid-cols-1 md:grid-cols-2 gap-6 p-4 mb-12">
      <!-- ... (content omitted for brevity, same as before) ... -->
      <!-- Left Side -->
      <div class="bg-white shadow rounded-2xl p-6 flex flex-col items-center h-fit">
        <h3 class="text-lg font-semibold text-gray-700 mb-4">{{ 'restaurant_menu' | translate }}</h3>
        <div class="w-full h-[500px] border rounded bg-gray-100 overflow-hidden relative">
            <iframe [src]="menuUrl()" class="w-full h-full" title="Restaurant Menu"></iframe>
        </div>
        <a [href]="menuUrl()" target="_blank" rel="noopener noreferrer" class="mt-4 bg-[#006494] text-white px-4 py-2 rounded hover:bg-[#005377] transition">
          {{ 'menu_button' | translate }}
        </a>
      </div>

      <!-- Right Side -->
      <div class="bg-white shadow rounded-2xl p-4 sm:p-8">
        @if (loadingConfig()) {
          <app-loading-spinner />
        } @else if (!isRestaurantActive()) {
           <div class="text-center py-10">
             <div class="bg-red-50 border border-red-200 text-red-700 p-6 rounded-xl">
               <h2 class="text-2xl font-bold mb-2">Restaurant Closed</h2>
               <p>The {{ restaurantId() }} restaurant is currently not accepting reservations.</p>
               <button (click)="router.navigate(['/'])" class="mt-4 text-blue-600 underline">Back to Home</button>
             </div>
           </div>
        } @else {
          <h2 class="text-2xl font-bold mb-6 text-gray-800">{{ 'book_table' | translate }}</h2>
          
          <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-5">
             <!-- Fields -->
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">{{ 'select_date' | translate }}</label>
              <select formControlName="date" class="w-full border p-3 rounded-md focus:ring-2 focus:ring-blue-500">
                <option value="">{{ 'select_date' | translate }}</option>
                @for (day of availableDates(); track day.iso) {
                  <option [value]="day.iso" [disabled]="day.disabled">
                    {{ day.label }} {{ day.disabled ? '(Unavailable)' : '' }}
                  </option>
                }
              </select>
              @if (spotsLeft() !== null && spotsLeft()! <= 4 && spotsLeft()! > 0) {
                <div class="text-yellow-600 text-sm mt-1 flex items-center gap-1">
                  <lucide-icon name="info" class="w-4 h-4"></lucide-icon> Only {{ spotsLeft() }} spots left!
                </div>
              }
              @if (spotsLeft() === 0) {
                <div class="text-red-600 text-sm mt-1">❌ Fully booked</div>
              }
            </div>

             <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Time</label>
              <select formControlName="time" class="w-full border p-2 rounded focus:ring-2 focus:ring-blue-500">
                @for (t of availableTimeSlots(); track t) {
                  <option [value]="t">{{ t }}</option>
                }
              </select>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">{{ 'number_of_guests' | translate }}</label>
              <select formControlName="guests" (change)="onGuestsChange()" class="w-full border p-2 rounded focus:ring-2 focus:ring-blue-500">
                @for (n of [1,2,3,4]; track n) {
                  <option [value]="n">{{ n }}</option>
                }
              </select>
            </div>

            <div class="grid grid-cols-2 gap-4">
              <input type="number" formControlName="room" [placeholder]="'room_number' | translate" class="w-full border p-2 rounded" />
              <input type="email" formControlName="email" [placeholder]="'email' | translate" class="w-full border p-2 rounded" />
            </div>
            <div class="grid grid-cols-2 gap-4">
              <input type="text" formControlName="first_name" [placeholder]="'first_name' | translate" class="w-full border p-2 rounded" />
              <input type="text" formControlName="last_name" [placeholder]="'last_name' | translate" class="w-full border p-2 rounded" />
            </div>

            @if (['Chinese', 'Indian', 'Italian'].includes(restaurantId() || '')) {
              <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                <label class="block text-gray-700 font-medium mb-3">
                  {{ 'select_main_course' | translate }} (Per Guest)
                </label>
                
                <div formArrayName="main_courses" class="space-y-3">
                  @for (control of mainCoursesArray.controls; track $index) {
                    <div class="flex flex-col sm:flex-row sm:items-center gap-3">
                      <span class="text-sm font-medium text-gray-500 w-16">Guest {{ $index + 1 }}:</span>
                      
                      @if (restaurantId() === 'Italian') {
                         <div class="flex flex-wrap gap-2">
                           @for (opt of italianOptions; track opt.val) {
                             <button type="button" 
                               [class.bg-yellow-100]="control.value === opt.val"
                               [class.border-yellow-400]="control.value === opt.val"
                               [class.text-yellow-800]="control.value === opt.val"
                               class="px-3 py-2 text-sm border rounded hover:bg-gray-50 transition"
                               (click)="control.setValue(opt.val)">
                               {{ opt.label | translate }}
                             </button>
                           }
                         </div>
                      } @else {
                        <div class="flex gap-2">
                          <button type="button" 
                             [class.bg-yellow-100]="control.value === 'chicken'"
                             class="px-4 py-2 border rounded hover:bg-gray-50"
                             (click)="control.setValue('chicken')">
                             {{ 'chicken' | translate }}
                          </button>
                          <button type="button" 
                             [class.bg-yellow-100]="control.value === 'meat'"
                             class="px-4 py-2 border rounded hover:bg-gray-50"
                             (click)="control.setValue('meat')">
                             {{ 'meat' | translate }}
                          </button>
                        </div>
                      }
                    </div>
                  }
                </div>
              </div>
            }

            @if (restaurantId() === 'Chinese' && hasSelectedSushi()) {
               <div class="bg-yellow-50 border border-yellow-200 p-3 rounded text-sm text-yellow-800">
                 <strong>🍣 Sushi Added:</strong> \${{ calculateSushiTotal() }} (Extra Charge)
               </div>
            }

            <textarea formControlName="comments" rows="3" [placeholder]="'comments_placeholder' | translate" class="w-full border p-2 rounded"></textarea>

            <button type="submit" [disabled]="form.invalid || submitting()" class="w-full bg-blue-600 text-white py-3 rounded-xl font-bold hover:bg-blue-700 disabled:bg-gray-400 transition">
              {{ submitting() ? ('sending' | translate) : ('confirm_reservation' | translate) }}
            </button>
          </form>
        }
      </div>
    </div>
    <!-- ... (Sushi Modal omitted, same as before) ... -->
  `
})
export class ReservationFormComponent implements OnInit {
  form!: FormGroup;
  restaurantId = signal<string | null>(null);
  loadingConfig = signal(true);
  submitting = signal(false);
  isRestaurantActive = signal(true);
  
  availableDates = signal<any[]>([]);
  availableTimeSlots = signal<string[]>(['19:00']);
  spotsLeft = signal<number | null>(null);
  showSushiModal = signal(false);

  // Static Data
  italianOptions = [
    { val: 'quatro_formagi', label: 'quatro_formagi' },
    { val: 'chicken_pizza', label: 'chicken_pizza' },
    { val: 'petto_chicken', label: 'petto_chicken' }
  ];

  sushiCategories = [
    { key: 'hot_rolls', label: 'sushi_categories.hot_rolls', items: [
      { name: 'Hot Dynamites', price: 4 }, { name: 'Hot Crab', price: 4 }, { name: 'Hot Dragon', price: 4 }
    ]},
    { key: 'maki_rolls', label: 'sushi_categories.maki_rolls', items: [
      { name: 'Sake Maki', price: 3 }, { name: 'Seagull Roll', price: 5 }, { name: 'Kappa Roll', price: 2 }, { name: 'Kabi Maki', price: 4 }
    ]}
  ];

  allSushiItems = this.sushiCategories.flatMap(c => c.items);

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    public router: Router,
    private reservationService: ReservationService,
    private configService: ConfigService,
    private capacityService: CapacityService,
    private toast: ToastrService
  ) {
    this.initForm();
    
    // ✅ Fix: Prevent memory leak
    this.form.get('date')?.valueChanges
      .pipe(takeUntilDestroyed())
      .subscribe(date => {
        if (date) this.checkCapacity(date);
      });
  }

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      const id = params.get('restaurantId');
      if (id) {
        this.restaurantId.set(id);
        this.loadConfigAndDates(id);
      }
    });
  }

  initForm() {
    this.form = this.fb.group({
      date: ['', Validators.required],
      time: ['19:00', Validators.required],
      guests: [2, Validators.required],
      room: ['', Validators.required],
      first_name: ['', Validators.required],
      last_name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      comments: [''],
      main_courses: this.fb.array([]),
      upsell_items: this.fb.group({})
    });

    const upsellGroup = this.form.get('upsell_items') as FormGroup;
    this.allSushiItems.forEach(item => {
      upsellGroup.addControl(item.name, this.fb.control(0));
    });

    // Initial setup for main courses
    this.onGuestsChange(); 
  }

  get mainCoursesArray() {
    return this.form.get('main_courses') as FormArray;
  }

  get upsellForm() {
    return this.form.get('upsell_items') as FormGroup;
  }

  // ✅ Fix: Preserve existing values when changing guest count
  onGuestsChange() {
    const currentCount = this.mainCoursesArray.length;
    const newCount = Number(this.form.get('guests')?.value || 0);

    if (newCount > currentCount) {
        for (let i = currentCount; i < newCount; i++) {
            this.mainCoursesArray.push(this.fb.control('', Validators.required));
        }
    } else if (newCount < currentCount) {
        for (let i = currentCount; i > newCount; i--) {
            this.mainCoursesArray.removeAt(i - 1);
        }
    }
  }

  async loadConfigAndDates(restaurant: string) {
    this.loadingConfig.set(true);
    try {
        const configs = await this.configService.getAll().toPromise();
        const myConfig = configs?.[restaurant];
        
        if (myConfig) {
            this.isRestaurantActive.set(myConfig.isActive);
            this.generateTimeSlots(myConfig.openingTime, myConfig.closingTime, myConfig.intervalMinutes);
        }

        const caps = await this.capacityService.getAll().toPromise();
        this.buildDateOptions(caps || {});
    } catch (e) {
        console.error(e);
        this.toast.error('Failed to load restaurant details');
    } finally {
        this.loadingConfig.set(false);
    }
  }

  buildDateOptions(capacities: any) {
    const dates = [];
    const today = new Date();
    const isTodayBlocked = today.getHours() >= 11;

    for (let i = 0; i < 6; i++) {
        const d = new Date();
        d.setDate(today.getDate() + i);
        const iso = d.toISOString().split('T')[0];
        const key = `${this.restaurantId()}_${iso}`;
        
        const capData = capacities[key];
        const capacity = capData?.capacity || 0;
        const reserved = capData?.reserved_guests || 0;
        const available = capacity - reserved;
        
        const disabled = (i === 0 && isTodayBlocked) || (!capacity) || (available <= 0);

        dates.push({
            iso,
            label: d.toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' }),
            disabled
        });
    }
    this.availableDates.set(dates);
  }

  checkCapacity(date: string) {
     const rest = this.restaurantId();
     if (!rest) return;
     
     this.reservationService.getAll(rest, date).subscribe(res => {
         this.capacityService.getAll().subscribe(allCaps => {
             const key = `${rest}_${date}`;
             const cap = allCaps[key]?.capacity || 0;
             const reserved = allCaps[key]?.reserved_guests || 0;
             this.spotsLeft.set(Math.max(0, cap - reserved));
         });
     });
  }

  generateTimeSlots(start: string, end: string, interval: number) {
      const slots = [];
      const [startH, startM] = start.split(':').map(Number);
      const [endH, endM] = end.split(':').map(Number);
      let current = new Date(); current.setHours(startH, startM, 0, 0);
      const endTime = new Date(); endTime.setHours(endH, endM, 0, 0);
      
      while (current <= endTime) {
          slots.push(current.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }));
          current.setMinutes(current.getMinutes() + interval);
      }
      this.availableTimeSlots.set(slots);
  }

  incrementSushi(name: string) {
    const ctrl = this.upsellForm.get(name);
    if (ctrl) {
      ctrl.setValue(ctrl.value + 1);
    }
  }
  
  decrementSushi(name: string) {
    const ctrl = this.upsellForm.get(name);
    if (ctrl && ctrl.value > 0) {
      ctrl.setValue(ctrl.value - 1);
    }
  }

  hasSelectedSushi() {
    const vals = this.upsellForm.value;
    return Object.values(vals).some((v: any) => v > 0);
  }

  calculateSushiTotal() {
     let total = 0;
     const vals = this.upsellForm.value;
     this.allSushiItems.forEach(item => {
        total += (vals[item.name] || 0) * item.price;
     });
     return total;
  }

  closeSushiModal() { this.showSushiModal.set(false); }

  onSubmit() {
    if (this.form.invalid) {
        this.toast.warning('Please fill in all required fields');
        return;
    }
    if (this.restaurantId() === 'Chinese') {
        this.showSushiModal.set(true);
    } else {
        this.finalizeReservation();
    }
  }

  submitWithSushi() {
    this.showSushiModal.set(false);
    this.finalizeReservation();
  }

  submitWithoutSushi() {
    this.upsellForm.reset();
    this.showSushiModal.set(false);
    this.finalizeReservation();
  }

  finalizeReservation() {
    this.submitting.set(true);
    const formData = this.form.value;
    
    const payload: any = {
        ...formData,
        restaurant: this.restaurantId(),
        upsell_total_price: this.calculateSushiTotal(),
        upsell_items: Object.fromEntries(
            Object.entries(formData.upsell_items).filter(([_, v]: any) => v > 0)
        )
    };

    this.reservationService.create(payload).subscribe({
        next: () => {
            this.toast.success('Reservation Confirmed! 🎉');
            this.router.navigate(['/confirmation']);
        },
        error: (err) => {
            console.error(err);
            this.toast.error(err.error?.detail || 'Booking failed');
            this.submitting.set(false);
        }
    });
  }

  menuUrl = () => `/menus/${this.restaurantId()}.pdf`;
}

<div class="max-w-6xl mx-auto pt-24 md:pt-28 grid grid-cols-1 md:grid-cols-2 gap-6 p-4 mb-12">

    <!-- Left Side: Menu Preview -->
    <div class="bg-white shadow rounded-2xl p-6 flex flex-col items-center h-fit">
        <h3 class="text-lg font-semibold text-gray-700 mb-4">Restaurant Menu</h3>

        @if (restaurant(); as rest) {
        <div class="w-full h-[500px] border rounded bg-gray-100 overflow-hidden relative">
            <iframe [src]="menuUrl()" class="w-full h-full" title="Restaurant Menu"></iframe>
        </div>
        <a [href]="rest.media.menuPdfUrl" target="_blank" rel="noopener noreferrer"
            class="mt-4 bg-[#006494] text-white px-4 py-2 rounded hover:bg-[#005377] transition">
            Download Menu PDF
        </a>
        }
    </div>

    <!-- Right Side: Form -->
    <div class="bg-white shadow rounded-2xl p-4 sm:p-8">
        @if (loadingConfig()) {
        <app-loading-spinner />
        } @else if (restaurant() && !restaurant()?.isActive) {
        <div class="text-center py-10">
            <div class="bg-red-50 border border-red-200 text-red-700 p-6 rounded-xl">
                <h2 class="text-2xl font-bold mb-2">Restaurant Closed</h2>
                <p>This restaurant is currently not accepting reservations.</p>
                <button (click)="router.navigate(['/'])" class="mt-4 text-blue-600 underline">Back to Home</button>
            </div>
        </div>
        } @else {
        <h2 class="text-2xl font-bold mb-6 text-gray-800">Book a Table</h2>

        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-5">
            <!-- Date, Time, Guests Fields -->
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Select Date</label>
                <select formControlName="date" class="w-full border p-3 rounded-md focus:ring-2 focus:ring-blue-500">
                    <option value="">Select Date</option>
                    @for (day of availableDates(); track day.iso) {
                    <option [value]="day.iso" [disabled]="day.disabled">
                        {{ day.label }} {{ day.disabled ? '(Unavailable)' : '' }}
                    </option>
                    }
                </select>
                @if (spotsLeft() !== null && spotsLeft()! <= 4 && spotsLeft()!> 0) {
                    <div class="text-yellow-600 text-sm mt-1 flex items-center gap-1">
                        <lucide-icon name="info" class="w-4 h-4"></lucide-icon> Only {{ spotsLeft() }} spots left!
                    </div>
                    }
                    @if (spotsLeft() === 0) {
                    <div class="text-red-600 text-sm mt-1">❌ Fully booked</div>
                    }
            </div>

            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Time</label>
                <select formControlName="time" class="w-full border p-2 rounded focus:ring-2 focus:ring-blue-500">
                    @for (t of availableTimeSlots(); track t) {
                    <option [value]="t">{{ t }}</option>
                    }
                </select>
            </div>

            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Number of Guests</label>
                <select formControlName="guests" (change)="onGuestsChange()"
                    class="w-full border p-2 rounded focus:ring-2 focus:ring-blue-500">
                    @for (n of [1,2,3,4]; track n) {
                    <option [value]="n">{{ n }}</option>
                    }
                </select>
            </div>

            <!-- User Details -->
            <div class="grid grid-cols-2 gap-4">
                <input type="number" formControlName="room" placeholder="Room Number"
                    class="w-full border p-2 rounded" />
                <input type="email" formControlName="email" placeholder="Email Address"
                    class="w-full border p-2 rounded" />
            </div>
            <div class="grid grid-cols-2 gap-4">
                <input type="text" formControlName="first_name" placeholder="First Name"
                    class="w-full border p-2 rounded" />
                <input type="text" formControlName="last_name" placeholder="Last Name"
                    class="w-full border p-2 rounded" />
            </div>

            <!-- Dynamic Main Courses -->
            @if (restaurant()?.menuConfig?.hasMainCourseSelection) {
            <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                <label class="block text-gray-700 font-medium mb-3">
                    {{ restaurant()?.menuConfig?.mainCourseLabel || 'Select Main Course' }} (Per Guest)
                </label>

                <div formArrayName="main_courses" class="space-y-3">
                    @for (control of mainCoursesArray.controls; track $index) {
                    <div class="flex flex-col sm:flex-row sm:items-center gap-3">
                        <span class="text-sm font-medium text-gray-500 w-16">Guest {{ $index + 1 }}:</span>

                        <div class="flex flex-wrap gap-2">
                            @for (opt of restaurant()?.menuConfig?.mainCourses; track opt.id) {
                            <button type="button" [class.bg-yellow-100]="control.value === opt.id"
                                [class.border-yellow-400]="control.value === opt.id"
                                [class.text-yellow-800]="control.value === opt.id"
                                class="px-3 py-2 text-sm border rounded hover:bg-gray-50 transition"
                                (click)="control.setValue(opt.id)">
                                {{ opt.label }}
                            </button>
                            }
                        </div>
                    </div>
                    }
                </div>
            </div>
            }

            <!-- Dynamic Upsell Summary -->
            @if (restaurant()?.menuConfig?.hasUpsells && hasSelectedSushi()) {
            <div class="bg-yellow-50 border border-yellow-200 p-3 rounded text-sm text-yellow-800">
                <strong>Extra Items Added:</strong> ${{ calculateSushiTotal() }}
            </div>
            }

            <textarea formControlName="comments" rows="3" placeholder="Any allergies or special requests?"
                class="w-full border p-2 rounded"></textarea>

            <button type="submit" [disabled]="form.invalid || submitting()"
                class="w-full bg-blue-600 text-white py-3 rounded-xl font-bold hover:bg-blue-700 disabled:bg-gray-400 transition">
                {{ submitting() ? 'Booking...' : 'Confirm Reservation' }}
            </button>
        </form>
        }
    </div>
</div>

<!-- Upsell Modal (Dynamic) -->
@if (showSushiModal()) {
<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
    <div class="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col">

        <div class="p-6 border-b flex justify-between items-center">
            <h3 class="text-xl font-bold text-gray-800">{{ restaurant()?.menuConfig?.upsellLabel }}</h3>
            <button (click)="closeSushiModal()" class="text-gray-400 hover:text-gray-600 text-2xl">&times;</button>
        </div>

        <div class="p-6 overflow-y-auto flex-1" [formGroup]="upsellForm">
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
                @for (item of restaurant()?.menuConfig?.upsellItems || []; track item.id) {
                <div class="flex justify-between items-center border-b pb-2">
                    <div>
                        <div class="font-medium text-gray-800">{{ item.label }}</div>
                        <div class="text-sm text-gray-500">${{ item.price }}</div>
                    </div>
                    <div class="flex items-center gap-3">
                        <button type="button" (click)="decrementSushi(item.id)"
                            class="w-8 h-8 rounded-full bg-gray-100 hover:bg-gray-200 text-gray-600 flex items-center justify-center font-bold">-</button>
                        <span class="w-6 text-center font-medium">{{ upsellForm.get(item.id)?.value || 0 }}</span>
                        <button type="button" (click)="incrementSushi(item.id)"
                            class="w-8 h-8 rounded-full bg-blue-100 hover:bg-blue-200 text-blue-600 flex items-center justify-center font-bold">+</button>
                    </div>
                </div>
                }
            </div>
        </div>

        <div class="p-6 border-t bg-gray-50 rounded-b-2xl flex justify-between items-center">
            <div>
                <span class="block text-xs text-gray-500 uppercase font-bold">Total Extra</span>
                <span class="text-2xl font-bold text-blue-600">${{ calculateSushiTotal() }}</span>
            </div>
            <div class="flex gap-3">
                <button (click)="submitWithoutSushi()"
                    class="px-4 py-2 text-gray-600 hover:bg-gray-200 rounded-lg transition">Skip</button>
                <button (click)="submitWithSushi()"
                    class="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg transition shadow-lg">Confirm
                    & Book</button>
            </div>
        </div>
    </div>
</div>
}
