// frontend/src/pages/admin/Login.jsx
import React, { useState } from 'react';
import { signInWithEmailAndPassword, getIdTokenResult } from "firebase/auth";
import { auth } from "@/firebase";
import { useNavigate, useLocation } from 'react-router-dom';



const Login = ({ onLogin }) => {
  const [password, setPassword] = useState('');
  const [showPw, setShowPw] = useState(false);
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [email, setEmail] = useState('');




  const navigate = useNavigate();
  const location = useLocation();
  const from = location.state?.from || '/admin/dashboard';

  const handleLogin = async (e) => {
    e?.preventDefault();
    if (!email.trim() || !password.trim()) {
      setError('Please enter email and password.');
      return;
    }
    setIsLoading(true);
    setError('');
    try {
      const cred = await signInWithEmailAndPassword(auth, email, password); // ← added back
      const tokenResult = await getIdTokenResult(cred.user, true);
      const role = tokenResult.claims.role || "";

      onLogin?.(cred.user);

      if (!role) {
        setError("Your account doesn't have a department assigned. Please contact an admin.");
        setIsLoading(false);
        return;
      }

      if (from && typeof from === "string") {
        if (role === "admin" && from.startsWith("/admin")) return navigate(from, { replace: true });
        if (role === "reception" && from.startsWith("/reception")) return navigate(from, { replace: true });
        if (role === "kitchen" && from.startsWith("/kitchen")) return navigate(from, { replace: true });
        if (role === "accounting" && from.startsWith("/accounting")) return navigate(from, { replace: true });
      }

      const fallback = {
        admin: "/admin/dashboard",
        reception: "/reception/dashboard",
        kitchen: "/kitchen/dashboard",
        accounting: "/accounting/dashboard",
      }[role] || "/admin/dashboard";

      navigate(fallback, { replace: true, state: { role } });
    } catch (err) {
      console.error('Login error:', err);
      setError(err.message || 'Login failed.');
    } finally {
      setIsLoading(false);
    }

  };

  return (
    // AuthLayout provides the outer layout & card
    <form onSubmit={handleLogin} className="space-y-6">
      <h2 className="text-xl font-semibold text-slate-900">Admin Portal</h2>


      {/* Email */}
      <div className="space-y-2">
        <label htmlFor="email" className="text-sm font-medium text-gray-700">
          Email
        </label>
        <input
          id="email"
          type="email"
          placeholder="name@example.com"
          className="w-full rounded-xl border border-gray-300 bg-white px-3 py-3 text-gray-900 placeholder:text-gray-400
                     focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-blue-600 transition"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          autoComplete="email"
        />
      </div>


      {/* Password field with icon + show/hide */}
      <div className="space-y-2">
        <label htmlFor="password" className="text-sm font-medium text-gray-700">
          Password
        </label>
        <div className="relative">
          <span className="pointer-events-none absolute inset-y-0 left-3 flex items-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5 text-gray-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth="1.8"
            >
              <path d="M7 10V8a5 5 0 0 1 10 0v2" />
              <rect x="5" y="10" width="14" height="10" rx="2" />
            </svg>
          </span>

          <input
            id="password"
            type={showPw ? 'text' : 'password'}
            placeholder="Enter your password"
            className="w-full rounded-xl border border-gray-300 bg-white pl-11 pr-11 py-3 text-gray-900 placeholder:text-gray-400
                       focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-blue-600 transition"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            autoComplete="current-password"
          />

          <button
            type="button"
            onClick={() => setShowPw((s) => !s)}
            className="absolute inset-y-0 right-3 flex items-center text-gray-400 hover:text-gray-600"
            aria-label={showPw ? 'Hide password' : 'Show password'}
          >
            {showPw ? (
              // Eye-off
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.8">
                <path d="M3 3l18 18" />
                <path d="M10.58 10.58A2 2 0 0 0 12 14a2 2 0 0 0 1.42-.58M9.88 5.1A9.76 9.76 0 0 1 12 5c6 0 9 7 9 7a17.39 17.39 0 0 1-3.06 3.94M6.24 6.24A17.93 17.93 0 0 0 3 12s3 7 9 7a9.8 9.8 0 0 0 3.06-.5" />
              </svg>
            ) : (
              // Eye
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.8">
                <path d="M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12Z" />
                <circle cx="12" cy="12" r="3" />
              </svg>
            )}
          </button>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div
          role="alert"
          className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700"
        >
          {error}
        </div>
      )}

      {/* Submit */}
      <button
        type="submit"
        disabled={isLoading}
        className={`w-full rounded-xl py-3 font-semibold text-white transition
          ${isLoading ? 'bg-blue-400 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-700 active:bg-blue-800'}`}
      >
        {isLoading ? 'Logging in…' : 'Login'}
      </button>

      <p className="text-center text-xs text-gray-500">
        Having trouble?{" "}
        <a href="mailto:omar.modrek@hurghadaseagull.com" className="underline hover:text-gray-700">Contact support</a>
      </p>
    </form>
  );
};

export default Login;

// hotel-reservation/src/app/features/auth/login/login.component.ts
// =================================================================================
// File: hotel-reservation/src/app/features/auth/login/login.component.ts
// =================================================================================

import { Component, signal, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush, // ✅ Performance Boost
  template: `
    <div
      class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8 bg-gray-50 dark:bg-gray-900"
    >
      <div class="sm:mx-auto sm:w-full sm:max-w-md">
        <h2
          class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900 dark:text-white"
        >
          Sign in to your account
        </h2>
      </div>

      <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-md">
        <form class="space-y-6" [formGroup]="form" (ngSubmit)="onSubmit()">
          <!-- Email -->
          <div class="space-y-2">
            <label for="email" class="text-sm font-medium text-gray-700">Email address</label>
            <input
              id="email"
              type="email"
              formControlName="email"
              placeholder="name@example.com"
              class="w-full rounded-xl border border-gray-300 bg-white px-3 py-3 text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-blue-600 transition"
            />
            @if (form.get('email')?.touched && form.get('email')?.invalid) {
            <p class="text-red-500 text-xs">Valid email is required</p>
            }
          </div>

          <!-- Password -->
      <div class="space-y-2">
        <label for="password" class="text-sm font-medium text-gray-700">Password</label>
        <div class="relative">
          <input
            id="password"
            [type]="showPassword() ? 'text' : 'password'"
            formControlName="password"
            placeholder="Enter your password"
            class="w-full rounded-xl border border-gray-300 bg-white pl-3 pr-11 py-3 text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-blue-600 transition"
          />
          <button
            type="button"
            (click)="togglePassword()"
            class="absolute inset-y-0 right-3 flex items-center text-gray-400 hover:text-gray-600"
          >
            @if (showPassword()) {
            <!-- Eye Off -->
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              stroke-width="1.8"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"
              />
            </svg>
            } @else {
            <!-- Eye -->
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              stroke-width="1.8"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
              />
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
              />
            </svg>
            }
          </button>
        </div>
      </div>

      <!-- Submit -->
      <button
        type="submit"
        [disabled]="form.invalid || isLoading()"
        class="w-full rounded-xl py-3 font-semibold text-white transition bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed"
      >
        {{ isLoading() ? 'Logging in...' : 'Login' }}
      </button>

      <p class="text-center text-xs text-gray-500">
        Having trouble?
        <a href="mailto:omar.modrek@hurghadaseagull.com" class="underline hover:text-gray-700"
          >Contact support</a
        >
      </p>
    </form>
  `,
})
export class LoginComponent {
  form;

  showPassword = signal(false);
  isLoading = signal(false);

  constructor(
    private fb: FormBuilder,
    private auth: AuthService,
    private router: Router,
    private toast: ToastrService
  ) {
    this.form = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
    });
  }

  togglePassword() {
    this.showPassword.update((v) => !v);
  }

  onSubmit() {
    if (this.form.invalid) return;

    this.isLoading.set(true);
    const { email, password } = this.form.value;

    this.auth.login(email!, password!).subscribe({
      next: ({ role }) => {
        this.toast.success('Welcome back!');
        this.redirectBasedOnRole(role);
      },
      error: (err) => {
        console.error(err);
        this.toast.error(err.message || 'Login failed');
        this.isLoading.set(false);
      },
    });
  }

  private redirectBasedOnRole(role: string) {
    const routes: Record<string, string> = {
      admin: '/admin/dashboard',
      reception: '/reception/dashboard',
      kitchen: '/kitchen/dashboard',
      accounting: '/accounting/dashboard',
    };
    this.router.navigate([routes[role] || '/admin/dashboard']);
  }
}
